Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_demo.Models
{
    public class Address
    {
        public List<SelectListItem> mycities = new List<SelectListItem>();

        public Address()
        {
            mycities.Add(new SelectListItem() { Text = "Agra", Value = "AgraCity" });
            mycities.Add(new SelectListItem() { Text = "Chennai", Value = "ChennaiCity" });
            mycities.Add(new SelectListItem() { Text = "Delhi", Value = "DelhiCity" });
            mycities.Add(new SelectListItem() { Text = "Bangalore", Value = "BangaloreCity" });
        }
            public string SelectedCity { get; set; }
    }

    }

Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace mvc_demo.Models
{
    public class Customer
    {
        [Required(ErrorMessage = "Id can not be empty")]
        public string Id { get; set; }
          

        [Required(ErrorMessage ="Name can not be empty")]
        [RegularExpression("[A-Za-z]*",ErrorMessage ="Invalid entry for name")]
        public string Name { get; set; }


        [Required(ErrorMessage ="Invalid phone number")]
        public string Phone { get; set; }
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace mvc_demo.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Username { get; set; }

        [ForeignKey("Username")]

        public LoginDetails Login { get; set; }


    }
}

Models/LoginDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace mvc_demo.Models
{
    public class LoginDetails
    {
        [Key]
        public string UserName { get; set; }

        public string Password { get; set; }

        public string Role { get; set; }

    }
}

Models/ReleaseManagementContext.cs
 using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace mvc_demo.Models
{
    public class ReleaseManagementContext : DbContext
    {
        public ReleaseManagementContext(): base("conRM")
        {

        }
        public DbSet<Employee> employee { get; set; }
        public DbSet<LoginDetails> loginDetails { get; set; }
    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc_demo.Models
{
    public class Student
    {
        public Student() { }

        public Student(int id, string name, int age)
        {
            Id = id;
            Name = name;
            Age = age;
        }

        public int Id 
        { get; set; }

        public string Name  
        { get; set; }

        public int Age 
        { get; set; }
    }
}

Controllers/ChangeLoginDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_demo.Controllers
{
    public class ChangeLoginDetailsController : Controller
    {
        // GET: ChangeLoginDetails
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_demo.Models;

namespace mvc_demo.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                    return RedirectToAction("index", customer);
                ModelState.AddModelError("ValidationError", "Some values are not valid");
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
            
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LayoutExampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_demo.Controllers
{
    public class LayoutExampleController : Controller
    {
        // GET: LayoutExample
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_demo.Models;

namespace mvc_demo.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UserLogin(LoginDetails loginDetails)
        {
            ReleaseManagementContext context = new ReleaseManagementContext();
            LoginDetails user = context.loginDetails
                                .FirstOrDefault(ud => ud.UserName == loginDetails.UserName && ud.Password == loginDetails.Password);

            if(user!= null)
            {
                TempData["username"] = loginDetails.UserName;
                 TempData["role"] = user.Role;
                return RedirectToAction("Index", "Student");
                    }
            return View();
        }

    }
}

Controllers/LoginUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_demo.Models;

namespace mvc_demo.Controllers
{
    public class LoginUserController : Controller
    {
        // GET: LoginUser
        ReleaseManagementContext db = new ReleaseManagementContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(LoginDetails loginDetails)
        {
            try
            {
                db.loginDetails.Add(loginDetails);
                db.SaveChanges();
                ViewBag.Message = "User created";
            }
            catch (Exception ex)
            {
                ViewBag.Message=ex.Message;
            }
            return View();
        }

    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_demo.Models;

namespace mvc_demo.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public string Index()
        {
            string userData = TempData.Peek("username").ToString() + " " + TempData.Peek("role").ToString();
            return userData;
        }
        [HttpGet]
        public ActionResult AnotherPage()
        {
            //view data is a dictionary
            //step 1

            ViewData["StudentName"] = "Ramu";
            int[] nums = { 1, 2, 34, 53, 5, 42 };

            //below snippet is for viewdata
            // ViewData["numbers"] = nums;


            //  below snippet is for viewbag
            ViewBag.numbers = nums;

            return View();
        }

        public ActionResult StudentDetails()
        {
            Student student = new Student(101, "Ramu", 23);
            return View(student);
        }

        public ActionResult SelectCity()
        {
            /*List<SelectListItem> mycities = new List<SelectListItem>();
            mycities.Add(new SelectListItem() { Text = "Agra", Value = "AgraCity" });
            mycities.Add(new SelectListItem() { Text = "Chennai", Value = "ChennaiCity" });
            mycities.Add(new SelectListItem() { Text = "Delhi", Value = "DelhiCity" });
            mycities.Add(new SelectListItem() { Text = "Bangalore", Value = "BangaloreCity" });
            return View();*/


            Address address = new Address();
            ViewBag.Cities = address.SelectedCity;
            return View(address);
        }
     
        [HttpPost]

          public string SelectCity(Address address)
          {
            return address.SelectedCity;
          }
    }
}

Views/Customer/Create.cshtml
@model mvc_demo.Models.Customer

@{
    ViewBag.Title = "Create";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/LayoutExample/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2>Index with layout</h2>

<hr/>



<div>
   @* @{
        Html.RenderPartial("PartialView");
    }
*@
    @Html.Partial("PartialView");
</div>

Views/Login/UserLogin.cshtml
@model mvc_demo.Models.LoginDetails

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserLogin</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>LoginDetails</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Not Registered yet?? Sign Up now!!!", "Register","LoginUser")
    </div>
</body>
</html>

Views/LoginUser/Register.cshtml
@model mvc_demo.Models.LoginDetails

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>LoginDetails</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <div>
        @ViewBag.Message
    </div>
</body>
</html>

Views/Shared/PartialView.cshtml
<h2>Partial View</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/Shared/_MyLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_MyLayout</title>
</head>
<body>
    <div> 

        <h2>This is my own layout </h2>

        @Html.ActionLink("DropDownSample","SelectCity","Student")
   
    <div>
        @RenderBody();
    </div>
    </div>
</body>
</html>

Views/Student/AnotherPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AnotherPage</title>
</head>
<body>
    <div>
        <h2>
            Its another page!!
        </h2>

        <div>
            Student name: @ViewData["StudentName"]
        </div>

        <!-- Below html code is for view data -->
        @*<div>
            Numbers:
            @foreach (var item in (IEnumerable<int>)( ViewData["numbers"]))
            {
                <p> @item  </p>
            }
        </div>*@


        <!-- Below html code is for view bag -->
        <div>
            Numbers:
            @foreach (var item in ViewBag.numbers)
            {
                <p> @item  </p>
            }
        </div>

    </div>
</body>
</html>

Views/Student/SelectCity.cshtml
@model mvc_demo.Models.Address
@{
    Layout = null;
}

<div>
    @{
        Html.RenderPartial("PartialView");
    }
</div>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SelectCity</title>
</head>
<body>
    <div>


        @using (Html.BeginForm())
        {
            @Html.DropDownListFor(m=>m.SelectedCity, new SelectList(Model.mycities, "Value", "Text"))
            <input type = "submit" value="SelectCity"/>
        }
        </div>
</body>
</html>

Views/Student/StudentDetails.cshtml
@model mvc_demo.Models.Student
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StudentDetails</title>
</head>
<body>
    <div>
        <p>Student ID: @Model.Id</p>
        <p>Student Name: @Model.Name</p>
        <p>Student Age: @Model.Age</p>
    </div>
</body>
</html>